---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: Vous devez installer et configurer les protocoles requis sur votre hôte avant de déployer Astra Trident. 
---
= Conditions préalables au déploiement
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer et configurer les protocoles requis sur votre hôte avant de déployer Astra Trident.



== Vérifier les exigences

* Vérifiez que votre déploiement répond à toutes les link:../trident-get-started/requirements.html["de formation"].
* Vérifiez que vous disposez d'une version prise en charge de Docker installée. Si votre version de Docker est obsolète, https://docs.docker.com/engine/install/["installez-le ou mettez-le à jour"^].
+
[listing]
----
docker --version
----
* Vérifiez que les conditions préalables au protocole sont installées et configurées sur votre hôte :


[cols="3*"]
|===
| Protocole | Système d'exploitation | Commandes 


| NFS  a| 
RHEL 8+
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`



| ISCSI  a| 
RHEL 8+
 a| 
. Installez les packages système suivants :
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. Vérifiez que la version iscsi-initiator-utils est 6.2.0.874-2.el7 ou ultérieure :
+
`rpm -q iscsi-initiator-utils`

. Définir la numérisation sur manuelle :
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Activer les chemins d'accès multiples :
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`

+

NOTE: Bien sûr `etc/multipath.conf` contient `find_multipaths no` sous `defaults`.

. S'assurer que `iscsid` et `multipathd` sont en cours d'exécution :
+
`sudo systemctl enable --now iscsid multipathd`

. Activer et démarrer `iscsi`:
+
`sudo systemctl enable --now iscsi`





| ISCSI  a| 
Ubuntu
 a| 
. Installez les packages système suivants :
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. Vérifiez que la version Open-iscsi est 2.0.874-5ubuntu2.10 ou ultérieure (pour bionique) ou 2.0.874-7.1ubuntu6.1 ou ultérieure (pour focaux) :
+
`dpkg -l open-iscsi`

. Définir la numérisation sur manuelle :
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Activer les chemins d'accès multiples :
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`

+

NOTE: Bien sûr `etc/multipath.conf` contient `find_multipaths no` sous `defaults`.

. S'assurer que `open-iscsi` et `multipath-tools` sont activées et en cours d'exécution :
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`



|===