---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Découvrez les options de configuration disponibles pour vos configurations Astra Trident. 
---
= Options de configuration du stockage
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les options de configuration disponibles pour vos configurations Astra Trident.



== Options de configuration globale

Ces options de configuration s'appliquent à toutes les configurations Astra Trident, quelle que soit la plateforme de stockage utilisée.

[cols="3*"]
|===
| Option | Description | Exemple 


| `version`  a| 
Numéro de version du fichier de configuration
 a| 
`1`



| `storageDriverName`  a| 
Nom du pilote de stockage
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| `storagePrefix`  a| 
Préfixe facultatif pour les noms de volumes. Valeur par défaut : `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restriction facultative sur les tailles de volume. Par défaut : « » (non appliqué)
 a| 
`10g`

|===

TIP: Ne pas utiliser `storagePrefix` (Y compris la valeur par défaut) pour les systèmes back-end Element. Par défaut, le `solidfire-san` le pilote ignore ce paramètre et n'utilise pas de préfixe. Nous vous recommandons d'utiliser un ID de tentID spécifique pour le mappage de volume Docker ou les données d'attributs renseignées par la version de Docker, les informations relatives au pilote et le nom brut de Docker dans les cas où il est possible d'utiliser une mundening de nom.

Les options par défaut sont disponibles pour éviter d'avoir à les spécifier sur chaque volume que vous créez. Le `size` option disponible pour tous les types de contrôleurs. Pour un exemple de définition de la taille de volume par défaut, reportez-vous à la section ONTAP configuration.

[cols="3*"]
|===
| Option | Description | Exemple 


| `size`  a| 
Taille par défaut facultative pour les nouveaux volumes. Valeur par défaut : `1G`
 a| 
`10G`

|===


== Configuration ONTAP

Outre les valeurs de configuration globale ci-dessus, lorsque vous utilisez ONTAP, les options de premier niveau suivantes sont disponibles.

[cols="3*"]
|===
| Option | Description | Exemple 


| `managementLIF`  a| 
Adresse IP de la LIF de management ONTAP. Vous pouvez spécifier un nom de domaine complet (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Adresse IP de la LIF de protocole.

*Pilotes NAS ONTAP*: Nous vous recommandons de spécifier `dataLIF`. Si elle n'est pas fournie, Astra Trident extrait les LIF de données du SVM. Vous pouvez spécifier un nom de domaine complet (FQDN) à utiliser pour les opérations de montage NFS, permettant de créer un DNS Round-Robin pour équilibrer la charge sur plusieurs LIF de données.

*Pilotes SAN ONTAP* : ne pas spécifier pour iSCSI. Astra Trident utilise link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappage de LUN sélectif ONTAP"^] Pour découvrir les LIFs iSCI nécessaires à l'établissement d'une session multi-chemin. Un avertissement est généré si `dataLIF` est explicitement défini.
 a| 
`10.0.0.2`



| `svm`  a| 
Storage Virtual machine à utiliser (requis, si la LIF de gestion est une LIF de cluster)
 a| 
`svm_nfs`



| `username`  a| 
Nom d'utilisateur pour la connexion au périphérique de stockage
 a| 
`vsadmin`



| `password`  a| 
Mot de passe pour se connecter au périphérique de stockage
 a| 
`secret`



| `aggregate`  a| 
Agrégat pour le provisionnement (facultatif ; si défini, doit être attribué au SVM) Pour le `ontap-nas-flexgroup` pilote, cette option est ignorée. Tous les agrégats affectés à un SVM sont utilisés pour provisionner un volume FlexGroup.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Facultatif, le provisionnement échoue si l'utilisation est supérieure à ce pourcentage
 a| 
`75%`



| `nfsMountOptions`  a| 
Contrôle granulaire des options de montage NFS ; par défaut : «-o nfssvers=3 ». *Disponible uniquement pour le `ontap-nas` et `ontap-nas-economy` pilotes*. https://["Pour plus d'informations sur la configuration de l'hôte NFS, consultez ici"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
ASTRA Trident crée et gère chaque nœud `igroups` comme `netappdvp`.

Cette valeur ne peut pas être modifiée ou omise.

*Disponible uniquement pour le `ontap-san` pilote*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Taille maximale du volume requesable et taille du volume parent qtree. *Pour le `ontap-nas-economy` Driver, cette option limite en outre la taille des volumes FlexVol qu'elle crée*.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Le nombre maximal de qtrees par FlexVol doit être compris dans la plage [50, 300], la valeur par défaut est 200. *Pour le `ontap-nas-economy` Pilote, cette option permet de personnaliser le nombre maximal de qtrees par FlexVol*.
 a| 
`300`

|===
Les options par défaut sont disponibles pour éviter d'avoir à les spécifier sur chaque volume que vous créez :

[cols="3*"]
|===
| Option | Description | Exemple 


| `spaceReserve`  a| 
Mode de réservation d'espace ; `none` (provisionnement fin) ou `volume` (épais)
 a| 
`none`



| `snapshotPolicy`  a| 
Règle Snapshot à utiliser ; la valeur par défaut est `none`
 a| 
`none`



| `snapshotReserve`  a| 
Pourcentage de réserve de snapshot. La valeur par défaut est « » pour accepter la valeur par défaut de ONTAP
 a| 
`10`



| `splitOnClone`  a| 
Séparer un clone de son parent lors de sa création. Par défaut, la valeur est `false`
 a| 
`false`



| `encryption`  a| 
Active NetApp Volume Encryption (NVE) sur le nouveau volume ; valeur par défaut sur `false`. Pour utiliser cette option, NVE doit être sous licence et activé sur le cluster.

Si NAE est activé sur le back-end, tous les volumes provisionnés dans Astra Trident seront activés par NAE.

Pour plus d'informations, se reporter à : link:../trident-reco/security-reco.html["Fonctionnement d'Astra Trident avec NVE et NAE"].
 a| 
vrai



| `unixPermissions`  a| 
L'option NAS pour les volumes NFS provisionnés est définie par défaut sur `777`
 a| 
`777`



| `snapshotDir`  a| 
Option NAS pour accéder à l' `.snapshot` répertoire, par défaut sur `false`
 a| 
`true`



| `exportPolicy`  a| 
L'option NAS pour la export policy NFS à utiliser est définie par défaut sur `default`
 a| 
`default`



| `securityStyle`  a| 
Option NAS pour l'accès au volume NFS provisionné.

Prise en charge de NFS `mixed` et `unix` styles de sécurité. La valeur par défaut est `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
OPTION SAN pour sélectionner le type de système de fichiers, par défaut sur `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Règle de Tiering à utiliser ; la règle par défaut est `none`; `snapshot-only` Pour la configuration SVM-DR antérieure à ONTAP 9.5
 a| 
`none`

|===


=== Options d'évolutivité

Le `ontap-nas` et `ontap-san` Les pilotes créent un ONTAP FlexVol pour chaque volume Docker. ONTAP prend en charge jusqu'à 1000 volumes FlexVol par nœud de cluster avec un cluster maximum de 12,000 volumes FlexVol. Si votre volume Docker répond à cette restriction, le `ontap-nas` Le pilote est la solution NAS préférée du fait des fonctionnalités supplémentaires offertes par les volumes FlexVol, telles que les snapshots et le clonage granulaires avec volume Docker.

Si vous avez besoin de plus de volumes Docker que ne peut pas être pris en charge par les limites FlexVol, choisissez la `ontap-nas-economy` ou le `ontap-san-economy` conducteur.

Le `ontap-nas-economy` Le pilote crée des volumes Docker en tant que qtrees ONTAP dans un pool de volumes FlexVol gérés automatiquement. Les qtrees offrent une évolutivité largement supérieure, jusqu'à 100,000 par nœud de cluster et 2,400,000 par cluster, au détriment de certaines fonctionnalités. Le `ontap-nas-economy` Le pilote ne prend pas en charge le clonage ou les snapshots granulaires volume Docker.


NOTE: Le `ontap-nas-economy` Le pilote n'est pas pris en charge par Docker Swarm, car Swarm n'effectue pas la création de volumes entre plusieurs nœuds.

Le `ontap-san-economy` Le pilote crée des volumes Docker en tant que LUN ONTAP dans un pool partagé de volumes FlexVol gérés automatiquement. De cette façon, chaque FlexVol n'est pas limité à un seul LUN et offre une meilleure évolutivité pour les charges de travail SAN. Selon les baies de stockage, ONTAP prend en charge jusqu'à 16384 LUN par cluster. Comme les volumes sont sous-LUN, ce pilote prend en charge les snapshots et le clonage granulaires par volume Docker.

Choisissez le `ontap-nas-flexgroup` pilote pour augmenter le parallélisme vers un seul volume qui peut atteindre plusieurs pétaoctets avec des milliards de fichiers. Les utilisations idéales de FlexGroups sont l'IA, LE ML, le Big Data et l'analytique, les logiciels, le streaming, les référentiels de fichiers, etc. Trident utilise tous les agrégats attribués à un SVM lors du provisionnement d'un volume FlexGroup. La prise en charge d'FlexGroup dans Trident comporte également plusieurs considérations :

* Requiert ONTAP version 9.2 ou supérieure
* À ce jour, FlexGroups prend uniquement en charge NFS v3.
* Recommandé pour activer les identifiants NFSv3 64 bits pour la SVM.
* La taille minimale recommandée de FlexGroup est de 100 Go.
* Le clonage n'est pas pris en charge pour FlexGroup volumes.


Pour plus d'informations sur FlexGroups et les workloads appropriés à FlexGroups, consultez le https://["NetApp FlexGroup Volume Guide des meilleures pratiques et de mise en œuvre"^].

Pour bénéficier de fonctionnalités avancées et d'une évolutivité massive dans le même environnement, vous pouvez exécuter plusieurs instances du plug-in de volume Docker, en utilisant une seule instance `ontap-nas` et une autre utilisation `ontap-nas-economy`.



=== Exemples de fichiers de configuration ONTAP

*Exemple NFS pour `ontap-nas` pilote*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*Exemple NFS pour `ontap-nas-flexgroup` pilote*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*Exemple NFS pour `ontap-nas-economy` pilote*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
*Exemple iSCSI pour `ontap-san` pilote*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
*Exemple NFS pour `ontap-san-economy` pilote*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----


== Configuration logicielle Element

Outre les valeurs de configuration globale, lorsque le logiciel Element (NetApp HCI/SolidFire) est utilisé, ces options sont disponibles.

[cols="3*"]
|===
| Option | Description | Exemple 


| `Endpoint`  a| 
\https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Port et adresse IP iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Locataire SolidFireF à utiliser (créé s'il n'est pas trouvé)
 a| 
`docker`



| `InitiatorIFace`  a| 
Spécifiez l'interface lors de la restriction du trafic iSCSI à une interface non-par défaut
 a| 
`default`



| `Types`  a| 
Spécifications de QoS
 a| 
Voir l'exemple ci-dessous



| `LegacyNamePrefix`  a| 
Préfixe des installations Trident mises à niveau. Si vous avez utilisé une version de Trident antérieure à 1.3.2 et que vous effectuez une mise à niveau avec des volumes existants, vous devez définir cette valeur pour accéder à vos anciens volumes mappés via la méthode nom-volume.
 a| 
`netappdvp-`

|===
Le `solidfire-san` Le pilote ne prend pas en charge Docker Swarm.



=== Exemple de fichier de configuration du logiciel Element

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----