---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-tridentctl.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Vous pouvez facilement mettre à niveau une installation Astra Trident existante à l"aide de `tridentctl`.' 
---
= Mise à niveau avec tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez facilement mettre à niveau une installation Astra Trident existante à l'aide de `tridentctl`.

.Description de la tâche
La désinstallation et la réinstallation d'Astra Trident fait office de mise à niveau. Lorsque vous désinstallez Trident, la demande de volume persistant et le volume persistant utilisés par l'Astra Trident. Les volumes persistants ayant déjà été provisionnés restent disponibles pendant la mise hors ligne d'Astra Trident, et Astra Trident provisionne les volumes pour les demandes de volume persistant créées dans l'intervalle une fois de nouveau en ligne.

.Avant de commencer
Révision link:upgrade-trident.html#select-an-upgrade-method["Sélectionnez une méthode de mise à niveau"] avant la mise à niveau avec `tridentctl`.

.Étapes
. Exécutez la commande de désinstallation dans `tridentctl` Pour supprimer toutes les ressources associées à Astra Trident, à l'exception des CRD et des objets associés.
+
[listing]
----
./tridentctl uninstall -n <namespace>
----
. Réinstallez Astra Trident. Reportez-vous à la section link:..trident-get-started/kubernetes-deploy-tridentctl.html["Installation d'Astra Trident à l'aide de tridentctl"].



IMPORTANT: N'interrompez pas le processus de mise à niveau. Assurez-vous que le programme d'installation s'exécute jusqu'à la fin.
