---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'ASTRA Trident suit une publication semestrielle, avec trois versions majeures chaque année. Chaque nouvelle version s"appuie sur les versions précédentes, offrant de nouvelles fonctionnalités et améliorations des performances ainsi que des correctifs et des améliorations. Nous vous encourageons à effectuer une mise à niveau au moins une fois par an pour profiter des nouvelles fonctionnalités d"Astra Trident.' 
---
= Mettez à niveau Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de la version 24.02, Astra Trident suit une publication tous les quatre mois, livrant trois versions majeures chaque année. Chaque nouvelle version exploite les versions précédentes et fournit de nouvelles fonctionnalités, des améliorations de performances, des correctifs et des améliorations. Nous vous encourageons à effectuer une mise à niveau au moins une fois par an pour profiter des nouvelles fonctionnalités d'Astra Trident.



== Considérations avant la mise à niveau

Lorsque vous mettez à niveau vers la dernière version d'Astra Trident, prenez en compte les points suivants :

* Il ne doit y avoir qu'une seule instance Astra Trident installée sur tous les namespaces d'un cluster Kubernetes donné.
* ASTRA Trident 23.07 et les versions ultérieures requièrent des snapshots de volume v1 et ne prennent plus en charge les snapshots alpha ou bêta.
* Si vous avez créé Cloud Volumes Service pour Google Cloud dans le link:../trident-use/gcp.html#learn-about-astra-trident-support-for-cloud-volumes-service-for-google-cloud["Type de service CVS"], vous devez mettre à jour la configuration back-end pour utiliser le `standardsw` ou `zoneredundantstandardsw` Niveau de service lors de la mise à niveau à partir d'Astra Trident 23.01. Impossible de mettre à jour le `serviceLevel` dans le back-end, les volumes pourraient tomber en panne. Reportez-vous à la section link:../trident-use/gcp.html#cvs-service-type-examples["Exemples de type de service CVS"] pour plus d'informations.
* Lors de la mise à niveau, il est important de fournir `parameter.fsType` dans `StorageClasses` Utilisé par Astra Trident. Vous pouvez supprimer et recréer `StorageClasses` sans interrompre les volumes existants.
+
** Il s'agit d'une exigence **** pour l'application https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["contextes de sécurité"^] Pour les volumes SAN.
** Le répertoire d'entrée https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample^] contient des exemples, tels que https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-basic.yaml.templ[`storage-class-basic.yaml.templ`^] et link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml`^].
** Pour plus d'informations, reportez-vous à la section link:../trident-rn.html["Problèmes connus"].






== Étape 1 : sélectionnez une version

Les versions d'Astra Trident suivent une date `YY.MM` convention de dénomination, où "YY" est les deux derniers chiffres de l'année et "MM" est le mois. Les versions point suivent un `YY.MM.X` convention, où « X » est le niveau de patch. Vous allez sélectionner la version à mettre à niveau en fonction de la version à partir de laquelle vous effectuez la mise à niveau.

* Vous pouvez effectuer une mise à niveau directe vers n'importe quelle version cible située dans une fenêtre à quatre versions de la version installée. Par exemple, vous pouvez effectuer une mise à niveau directe de la version 23.04 (ou de toute version 23.04 points) vers la version 24.06.
* Si vous effectuez une mise à niveau à partir d'une version en dehors de la fenêtre à quatre versions, effectuez une mise à niveau en plusieurs étapes. Suivez les instructions de mise à link:../earlier-versions.html["version antérieure"] niveau de pour effectuer la mise à niveau vers la version la plus récente qui s'adapte à la fenêtre à quatre versions. Par exemple, si vous exécutez 22.01 et que vous souhaitez effectuer une mise à niveau vers 24.06 :
+
.. Première mise à niveau de 22.07 à 23.04.
.. Puis passez de 23.04 à 24.06.





NOTE: Lorsque vous effectuez une mise à niveau avec l'opérateur Trident sur OpenShift Container Platform, vous devez effectuer une mise à niveau vers Trident 21.01.1 ou une version ultérieure. L'opérateur Trident sorti avec 21.01.0 contient un problème connu qui a été résolu en 21.01.1. Pour plus de détails, reportez-vous au https://github.com/NetApp/trident/issues/517["Consultez le document GitHub pour plus d'informations"^].



== Étape 2 : déterminer la méthode d'installation d'origine

Pour déterminer quelle version vous avez utilisée pour l'installation initiale d'Astra Trident :

. Utiliser `kubectl get pods -n trident` pour examiner les pods.
+
** S'il n'y a pas de pod opérateur, Astra Trident a été installé avec `tridentctl`.
** S'il existe un pod opérateur, Astra Trident a été installé à l'aide de l'opérateur Trident soit manuellement, soit à l'aide d'Helm.


. S'il y a un boîtier opérateur, utiliser `kubectl describe torc` Pour déterminer si Astra Trident a été installé à l'aide d'Helm.
+
** S'il y a une étiquette Helm, Astra Trident a été installée à l'aide d'Helm.
** S'il n'y a pas d'étiquette Helm, Astra Trident a été installé manuellement à l'aide de l'opérateur Trident.






== Étape 3 : sélectionnez une méthode de mise à niveau

En général, vous devez effectuer une mise à niveau en utilisant la même méthode que celle utilisée pour l'installation initiale, mais vous pouvez le faire link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["passer d'une méthode d'installation à l'autre"]. Il existe deux options de mise à niveau d'Astra Trident.

* link:upgrade-operator.html["Mise à niveau à l'aide de l'opérateur Trident"]
+

TIP: Nous vous suggérons de revoir link:upgrade-operator-overview.html["Comprendre le workflow de mise à niveau de l'opérateur"] avant la mise à niveau avec l'opérateur.

* 

