---
sidebar: sidebar 
permalink: trident-use/backends.html 
keywords: backends, storage system, anf, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, fsx 
summary: Un système back-end définit la relation entre Astra Trident et un système de stockage. Il explique à Astra Trident comment communiquer avec ce système de stockage et comment Astra Trident doit provisionner des volumes à partir de celui-ci. 
---
= Configuration des systèmes back-end
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un système back-end définit la relation entre Astra Trident et un système de stockage. Il explique à Astra Trident comment communiquer avec ce système de stockage et comment Astra Trident doit provisionner des volumes à partir de celui-ci.

Astra Trident propose automatiquement des pools de stockage back-end correspondant aux exigences définies par une classe de stockage. Découvrez comment configurer le système back-end pour votre système de stockage.

* link:anf.html["Configurer un back-end Azure NetApp Files"^]
* link:gcp.html["Configurer un système back-end Cloud Volumes Service pour Google Cloud Platform"^]
* link:element.html["Configurer un système NetApp HCI ou SolidFire backend"^]
* link:ontap-nas.html["Configurer un système back-end avec des pilotes NAS ONTAP ou Cloud Volumes ONTAP"^]
* link:ontap-san.html["Configurer un système back-end avec des pilotes ONTAP ou Cloud Volumes ONTAP SAN"^]
* link:trident-fsx.html["Utilisez Astra Trident avec Amazon FSX pour NetApp ONTAP"^]

