---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Découvrez comment configurer un back-end ONTAP avec les pilotes SAN ONTAP. 
---
= Présentation du pilote SAN ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment configurer un back-end ONTAP avec les pilotes ONTAP et Cloud Volumes ONTAP SAN.



== Détails du pilote SAN ONTAP

ASTRA Trident fournit les pilotes de stockage SAN suivants pour communiquer avec le cluster ONTAP. Les modes d'accès pris en charge sont : _ReadWriteOnce_ (RWO), _ReadOnlyMey_ (ROX), _ReadWriteMaly_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Si vous utilisez Astra Control pour la protection, la restauration et la mobilité, lisez <<Compatibilité du pilote Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Conducteur | Protocole | Mode Volume | Modes d'accès pris en charge | Systèmes de fichiers pris en charge 


| `ontap-san`  a| 
ISCSI
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Pas de système de fichiers, périphérique de bloc brut



| `ontap-san`  a| 
ISCSI
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode de volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Pas de système de fichiers, périphérique de bloc brut



| `ontap-san-economy`  a| 
ISCSI
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode de volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`

|===


=== Compatibilité du pilote Astra Control

Astra Control assure une protection, une reprise d'activité et une mobilité transparentes (en déplaçant des volumes entre les clusters Kubernetes) pour les volumes créés avec le système `ontap-nas`, `ontap-nas-flexgroup`, et `ontap-san` pilotes. Voir link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Conditions préalables à la réplication d'Astra Control"^] pour plus d'informations.

[WARNING]
====
* Utiliser `ontap-san-economy` uniquement si le nombre d'utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP prises en charge"^].
* Utiliser `ontap-nas-economy` uniquement si le nombre d'utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP prises en charge"^] et le `ontap-san-economy` le pilote ne peut pas être utilisé.
* Ne pas utiliser `ontap-nas-economy` si vous prévoyez d'avoir besoin en termes de protection des données, de reprise sur incident ou de mobilité.


====


== Autorisations utilisateur

Astra Trident devrait être exécuté en tant qu'administrateur de ONTAP ou du SVM, généralement à l'aide du `admin` utilisateur du cluster ou un `vsadmin` Utilisateur d'un SVM ou un utilisateur avec un autre nom qui a le même rôle. Pour les déploiements Amazon FSX pour NetApp ONTAP, Astra Trident devrait être exécuté en tant qu'administrateur ONTAP ou SVM, à l'aide du cluster `fsxadmin` utilisateur ou un `vsadmin` Utilisateur d'un SVM ou un utilisateur avec un autre nom qui a le même rôle. Le `fsxadmin` l'utilisateur remplace limitée l'utilisateur administrateur du cluster.


NOTE: Si vous utilisez le `limitAggregateUsage` paramètre, des autorisations d'administration du cluster sont requises. Avec Amazon FSX pour NetApp ONTAP avec Astra Trident, le `limitAggregateUsage` le paramètre ne fonctionne pas avec le `vsadmin` et `fsxadmin` comptes d'utilisateur. L'opération de configuration échoue si vous spécifiez ce paramètre.

S'il est possible de créer au sein de ONTAP un rôle plus restrictif qu'un pilote Trident peut utiliser, nous ne le recommandons pas. La plupart des nouvelles versions de Trident appellent des API supplémentaires qui devront être prises en compte, ce qui complique les mises à niveau et risque d'erreurs.
