---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, astra trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: 'Vous pouvez déployer l"opérateur Trident et installer Astra Trident à l"aide de Helm. Ce processus s"applique aux installations dans lesquelles les images de conteneur requises par Astra Trident sont stockées dans un registre privé.' 
---
= Déploiement de l'opérateur Trident à l'aide de Helm (mode hors ligne)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déployer l'opérateur Trident et installer Astra Trident à l'aide de Helm. Ce processus s'applique aux installations dans lesquelles les images de conteneur requises par Astra Trident sont stockées dans un registre privé. Si vous ne disposez pas d'un registre d'images privé, utilisez le link:kubernetes-deploy-helm.html["du déploiement standard"].



== Informations stratégiques sur Astra Trident 23.07

*Vous devez lire les renseignements essentiels suivants sur Astra Trident.*

.<strong> informations pratiques sur le Tridécouvrez Astra </strong>
[%collapsible%open]
====
* Kubernetes 1.27 est désormais pris en charge dans Trident. Mise à niveau de Trident avant la mise à niveau de Kubernetes.
* Astra Trident applique rigoureusement l'utilisation de la configuration de chemins d'accès multiples dans les environnements SAN, avec la valeur recommandée de `find_multipaths: no` dans le fichier multipath.conf.
+
Utilisation d'une configuration sans chemins d'accès multiples ou de l'utilisation de `find_multipaths: yes` ou `find_multipaths: smart` la valeur du fichier multipath.conf entraînera des échecs de montage. Trident a recommandé l'utilisation de `find_multipaths: no` depuis la version 21.07.



====


== Déployer l'opérateur Trident et installer Astra Trident à l'aide de Helm

Avec Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Graphique Helm"^] Vous pouvez déployer l'opérateur Trident et installer Trident en une étape.

Révision link:../trident-get-started/kubernetes-deploy.html["présentation de l'installation"] pour vous assurer que les conditions préalables à l'installation sont respectées et que vous avez sélectionné l'option d'installation appropriée pour votre environnement.

.Avant de commencer
En plus du link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["conditions préalables au déploiement"] dont vous avez besoin link:https://v3.helm.sh/["Version 3 de Helm"^].

.Étapes
. Ajout du référentiel Astra Trident Helm :
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Utiliser `helm install` et spécifiez un nom pour votre déploiement et l'emplacement du registre d'images. Votre link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Images Trident et CSI"] Peut être situé dans un registre ou dans des registres différents, mais toutes les images CSI doivent se trouver dans le même registre. Dans les exemples, `23.07.1` Est la version d'Astra Trident que vous installez.
+
[role="tabbed-block"]
====
.Images dans un registre
--
[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.07.1 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace>
----
--
.Images dans différents registres
--
Vous devez ajouter `sig-storage` à la `imageRegistry` pour utiliser différents emplacements de registre.

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.07.1 --set imageRegistry=<your-registry>/sig-storage --set operatorImage=<your-registry>/netapp/trident-operator:23.07.1 --set tridentAutosupportImage=<your-registry>/netapp/trident-autosupport:23.07 --set tridentImage=<your-registry>/netapp/trident:23.07.1 --create-namespace --namespace <trident-namespace>
----
--
====
+

NOTE: Si vous avez déjà créé un namespace pour Trident, le `--create-namespace` le paramètre ne crée pas d'espace de noms supplémentaire.



Vous pouvez utiliser `helm list` pour vérifier les détails de l'installation tels que le nom, l'espace de noms, le graphique, l'état, la version de l'application, et numéro de révision.



== Transmettre les données de configuration pendant l'installation

Il existe deux façons de passer les données de configuration au cours de l'installation :

[cols="2"]
|===
| Option | Description 


| `--values` (ou `-f`)  a| 
Spécifiez un fichier YAML avec les remplacements. Ceci peut être spécifié plusieurs fois et le fichier le plus à droite sera prioritaire.



| `--set`  a| 
Spécifiez les remplacements sur la ligne de commande.

|===
Par exemple, pour modifier la valeur par défaut de `debug`, exécutez ce qui suit `--set` commande où `23.07.1` Est la version d'Astra Trident que vous installez :

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.07.1  --create-namespace --namespace trident --set tridentDebug=true
----


== Options de configuration

Ce tableau et le `values.yaml` Le fichier, qui fait partie du graphique Helm, fournit la liste des clés et leurs valeurs par défaut.

[cols="3"]
|===
| Option | Description | Valeur par défaut 


| `nodeSelector` | Libellés des nœuds pour l'affectation des pods |  


| `podAnnotations` | Annotations de pod |  


| `deploymentAnnotations` | Annotations de déploiement |  


| `tolerations` | Tolérances pour l'affectation de pod |  


| `affinity` | Affinité pour l'affectation de pod |  


| `tridentControllerPluginNodeSelector` | Sélecteurs de nœuds supplémentaires pour les pods. Reportez-vous à la section <<Présentation des pods de contrôleur et des nœuds>> pour plus d'informations. |  


| `tridentControllerPluginTolerations` | Remplace les tolérances Kubernetes pour les pods. Reportez-vous à la section <<Présentation des pods de contrôleur et des nœuds>> pour plus d'informations. |  


| `tridentNodePluginNodeSelector` | Sélecteurs de nœuds supplémentaires pour les pods. Reportez-vous à la section <<Présentation des pods de contrôleur et des nœuds>> pour plus d'informations. |  


| `tridentNodePluginTolerations` | Remplace les tolérances Kubernetes pour les pods. Reportez-vous à la section <<Présentation des pods de contrôleur et des nœuds>> pour plus d'informations. |  


| `imageRegistry` | Identifie le registre du `trident-operator`, `trident`, et autres images. Laissez vide pour accepter la valeur par défaut. | « » 


| `imagePullPolicy` | Définit la stratégie d'extraction d'image pour le `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Définit les secrets d'extraction d'image pour le `trident-operator`, `trident`, et autres images. |  


| `kubeletDir` | Permet de remplacer l'emplacement hôte de l'état interne du kubelet. | '"/var/lib/kubelet"' 


| `operatorLogLevel` | Permet de définir le niveau du journal de l'opérateur Trident sur : `trace`, `debug`, `info`, `warn`, `error`, ou `fatal`. | `"info"` 


| `operatorDebug` | Permet de définir le niveau du journal de l'opérateur Trident sur DEBUG. | `true` 


| `operatorImage` | Permet la neutralisation complète de l'image pour `trident-operator`. | « » 


| `operatorImageTag` | Permet de remplacer la balise du `trident-operator` image. | « » 


| `tridentIPv6` | Permet à Astra Trident de fonctionner dans des clusters IPv6. | `false` 


| `tridentK8sTimeout` | Remplace le délai d'expiration par défaut de 30 secondes pour la plupart des opérations de l'API Kubernetes (s'il n'est pas égal à zéro, en secondes). | `0` 


| `tridentHttpRequestTimeout` | Remplace le délai par défaut de 90 secondes pour les requêtes HTTP, par `0s` étant une durée infinie pour le délai d'expiration. Les valeurs négatives ne sont pas autorisées. | `"90s"` 


| `tridentSilenceAutosupport` | Permet de désactiver le reporting AutoSupport périodique d'Astra Trident. | `false` 


| `tridentAutosupportImageTag` | Permet de remplacer la balise de l'image pour le conteneur AutoSupport Astra Trident. | `<version>` 


| `tridentAutosupportProxy` | Permet au conteneur AutoSupport Astra Trident de Phone Home via un proxy HTTP. | « » 


| `tridentLogFormat` | Définit le format de journalisation d'Astra Trident (`text` ou `json`). | `"text"` 


| `tridentDisableAuditLog` | Désactive l'enregistreur d'audit Astra Trident. | `true` 


| `tridentLogLevel` | Permet de définir le niveau de journal d'Astra Trident sur : `trace`, `debug`, `info`, `warn`, `error`, ou `fatal`. | `"info"` 


| `tridentDebug` | Permet de définir le niveau du journal d'Astra Trident sur `debug`. | `false` 


| `tridentLogWorkflows` | Permet d'activer des workflows Astra Trident spécifiques pour la journalisation des traces ou la suppression de journaux. | « » 


| `tridentLogLayers` | Permet d'activer des couches Astra Trident spécifiques pour la journalisation des traces ou la suppression des journaux. | « » 


| `tridentImage` | Permet la neutralisation complète de l'image pour Astra Trident. | « » 


| `tridentImageTag` | Permet de remplacer la balise de l'image pour Astra Trident. | « » 


| `tridentProbePort` | Permet de remplacer le port par défaut utilisé pour les sondes de disponibilité/préparation Kubernetes. | « » 


| `windows` | Permet d'installer Astra Trident sur le nœud de travail Windows. | `false` 


| `enableForceDetach` | Permet d'activer la fonction forcer le détachement. | `false` 


| `excludePodSecurityPolicy` | Exclut la stratégie de sécurité du module opérateur de la création. | `false` 
|===


== Et la suite
