---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, tridentctl, windows 
summary: 'Vous pouvez installer Astra Trident à l"aide de `tridentctl`. Ce processus s"applique aux installations où les images de conteneur requises par Astra Trident sont stockées dans un registre privé ou non.' 
---
= Installation à l'aide de tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer Astra Trident à l'aide de `tridentctl`. Ce processus s'applique aux installations où les images de conteneur requises par Astra Trident sont stockées dans un registre privé ou non. Pour personnaliser votre `tridentctl` déploiement, voir link:kubernetes-customize-deploy-tridentctl.html["Personnalisez le déploiement tridentctl"].



== Informations stratégiques sur Astra Trident 23.07

*Vous devez lire les renseignements essentiels suivants sur Astra Trident.*

.<strong> informations pratiques sur le Tridécouvrez Astra </strong>
[%collapsible%open]
====
* Kubernetes 1.27 est désormais pris en charge dans Trident. Mise à niveau de Trident avant la mise à niveau de Kubernetes.
* Astra Trident applique rigoureusement l'utilisation de la configuration de chemins d'accès multiples dans les environnements SAN, avec la valeur recommandée de `find_multipaths: no` dans le fichier multipath.conf.
+
Utilisation d'une configuration sans chemins d'accès multiples ou de l'utilisation de `find_multipaths: yes` ou `find_multipaths: smart` la valeur du fichier multipath.conf entraînera des échecs de montage. Trident a recommandé l'utilisation de `find_multipaths: no` depuis la version 21.07.



====


== Installation d'Astra Trident à l'aide de `tridentctl`

Révision link:../trident-get-started/kubernetes-deploy.html["présentation de l'installation"] pour vous assurer que les conditions préalables à l'installation sont respectées et que vous avez sélectionné l'option d'installation appropriée pour votre environnement.

.Avant de commencer
Avant de commencer l'installation, connectez-vous à l'hôte Linux et vérifiez qu'il gère un travail. link:requirements.html["Cluster Kubernetes pris en charge"^] et que vous disposez des privilèges nécessaires.


NOTE: Avec OpenShift, utilisez `oc` au lieu de `kubectl` dans tous les exemples qui suivent, et connectez-vous en tant que *system:admin* en premier lieu en cours d'exécution `oc login -u system:admin` ou `oc login -u kube-admin`.

[%collapsible%open]
====
. Vérifiez votre version Kubernetes :
+
[listing]
----
kubectl version
----
. Vérifiez les privilèges d'administrateur du cluster :
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Vérifiez que vous pouvez lancer un pod qui utilise une image depuis Docker Hub et atteindre votre système de stockage sur le réseau du pod :
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== Étape 1 : téléchargez le package du programme d'installation de Trident

Le package du programme d'installation Astra Trident crée un pod Trident, configure les objets CRD utilisés pour maintenir son état et initialise les sidecars CSI pour effectuer des actions telles que le provisionnement et la connexion de volumes aux hôtes du cluster. Téléchargez et extrayez la dernière version du programme d'installation de Trident link:https://github.com/NetApp/trident/releases/latest["La section _Assets_ sur GitHub"^]. Mettez à jour _<trident-installer-XX.XX.X.tar.gz>_ dans l'exemple avec la version Trident Astra que vous avez sélectionnée.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v23.07.1/trident-installer-23.07.1.tar.gz
tar -xf trident-installer-23.07.1.tar.gz
cd trident-installer
----


== Étape 2 : installer Astra Trident

Installez Astra Trident dans l'espace de noms souhaité en exécutant le `tridentctl install` commande. Vous pouvez ajouter des arguments supplémentaires pour spécifier l'emplacement du registre d'images.

[role="tabbed-block"]
====
.Mode standard
--
[listing]
----
./tridentctl install -n trident
----
--
.Images dans un registre
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:23.07 --trident-image <your-registry>/trident:23.07.1
----
--
.Images dans différents registres
--
Vous devez ajouter `sig-storage` à la `imageRegistry` pour utiliser différents emplacements de registre.

[listing]
----
./tridentctl install -n trident --image-registry <your-registry>/sig-storage --autosupport-image <your-registry>/netapp/trident-autosupport:23.07 --trident-image <your-registry>/netapp/trident:23.07.1
----
--
====
L'état de votre installation devrait ressembler à ceci.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=23.07.1
INFO Trident installation succeeded.
....
----


== Vérifiez l'installation

Vous pouvez vérifier votre installation à l'aide de l'état de création du pod ou `tridentctl`.



=== Utilisation du statut de création du pod

Vous pouvez vérifier que l'installation d'Astra Trident est terminée en consultant le statut des pods créés :

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: Si le programme d'installation ne s'est pas terminé correctement ou `trident-controller-<generated id>` (`trident-csi-<generated id>` Dans les versions antérieures à 23.01) n'ont pas d'état *en cours d'exécution*, la plate-forme n'était pas installée. Utiliser `-d` à link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["activer le mode débogage"] et de résoudre le problème.



=== À l'aide de `tridentctl`

Vous pouvez utiliser `tridentctl` Pour vérifier la version d'Astra Trident installée.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.07.1        | 23.07.1        |
+----------------+----------------+
----


== Exemples de configurations

.Exemple 1 : activez Astra Trident pour qu'elle s'exécute sur les nœuds Windows
[%collapsible%open]
====
Pour permettre l'exécution d'Astra Trident sur les nœuds Windows :

[listing]
----
tridentctl install --windows -n trident
----
====
.Exemple 2 : activer le détachement forcé
[%collapsible%open]
====
Pour plus d'informations sur le détachement forcé, voir link:..trident-get-started/kubernetes-customize-deploy.html["Personnalisez l'installation de l'opérateur Trident"].

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====