---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, astra trident, hci, netapp hci, storage system, access volumes, 
summary: 'Découvrez comment Astra Trident utilise les groupes d"accès de volume.' 
---
= Groupes d'accès de volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez l'utilisation d'Astra Trident https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["groupes d'accès de volume"^].


NOTE: Ignorez cette section si vous utilisez CHAP, qui est recommandé pour simplifier la gestion et éviter la limite de mise à l'échelle décrite ci-dessous. De plus, si vous utilisez Astra Trident en mode CSI, vous pouvez ignorer cette section. Astra Trident utilise CHAP lorsqu'il est installé en tant que mécanisme de provisionnement CSI amélioré.



== En savoir plus sur les groupes d'accès aux volumes

Astra Trident peut utiliser des groupes d'accès de volume pour contrôler l'accès aux volumes qu'il provisionne. Si CHAP est désactivé, il attend de trouver un groupe d'accès appelé `trident` Sauf si vous spécifiez un ou plusieurs ID de groupe d'accès dans la configuration.

ASTRA Trident associe de nouveaux volumes aux groupes d'accès configurés, mais il ne crée pas et ne gère pas les groupes d'accès eux-mêmes. Les groupes d'accès doivent exister avant l'ajout du système back-end de stockage à Astra Trident et doivent contenir les IQN iSCSI de chaque nœud du cluster Kubernetes pouvant potentiellement monter les volumes provisionnés par ce back-end. Dans la plupart des installations, cela inclut tous les nœuds workers dans le cluster.

Pour les clusters Kubernetes de plus de 64 nœuds, vous devez utiliser plusieurs groupes d'accès. Chaque groupe d'accès peut contenir jusqu'à 64 IQN et chaque volume peut appartenir à quatre groupes d'accès. Avec quatre groupes d'accès configurés au maximum, n'importe quel nœud d'un cluster de 256 nœuds maximum pourra accéder à n'importe quel volume. Pour connaître les dernières limites relatives aux groupes d'accès aux volumes, reportez-vous à la section https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["ici"^].

Si vous modifiez la configuration à partir d'une configuration utilisant la configuration par défaut `trident` Groupe d'accès à un groupe qui utilise également d'autres, inclure l'ID pour le `trident` groupe d'accès dans la liste.
