---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Découvrez tridentctl, un utilitaire de ligne de commandes permettant un accès simple à Trident. 
---
= Gérez Astra Trident à l'aide de tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le https://github.com/NetApp/trident/releases["Pack d'installation Trident"^] inclut le `tridentctl` Utilitaire de ligne de commande pour un accès simple à Astra Trident. Les utilisateurs Kubernetes disposant de privilèges suffisants peuvent l'utiliser pour installer Astra Trident ou gérer le namespace qui contient le pod Astra Trident.



== Commandes et indicateurs globaux

Vous pouvez exécuter `tridentctl help` pour obtenir une liste des commandes disponibles pour `tridentctl` ou ajoutez le `--help` marquer n'importe quelle commande pour obtenir une liste d'options et d'indicateurs pour cette commande spécifique.

Du stockage::


[listing]
----
tridentctl [command] [--optional-flag]
----
ASTRA Trident `tridentctl` l'utilitaire prend en charge les commandes et indicateurs globaux suivants.

.Commandes
[%collapsible]
====
`create`:: Ajoutez une ressource à Astra Trident.
`delete`:: Supprimez une ou plusieurs ressources d'Astra Trident.
`get`:: Obtenez une ou plusieurs ressources d'Astra Trident.
`help`:: Aide sur n'importe quelle commande.
`images`:: Imprimez un tableau des images de conteneur dont Astra Trident a besoin.
`import`:: Importez une ressource existante dans Astra Trident.
`install`:: Installer Astra Trident.
`logs`:: Imprimez les journaux depuis Astra Trident.
`send`:: Envoyer une ressource depuis Astra Trident.
`uninstall`:: Désinstallez Astra Trident.
`update`:: Modifier une ressource dans Astra Trident.
`update backend state`:: Suspendre temporairement les opérations back-end.
`upgrade`:: Mise à niveau d'une ressource dans Astra Trident
`version`:: Imprimez la version d'Astra Trident.


====
.Alarmes globales
[%collapsible]
====
`-d`, `--debug`:: Sortie de débogage.
`-h`, `--help`:: Aide pour `tridentctl`.
`-n`, `--namespace string`:: Espace de noms du déploiement d'Astra Trident.
`-o`, `--output string`:: Format de sortie. Un de json|yaml|nom|large|ps (par défaut).
`-s`, `--server string`:: Adresse/port de l'interface REST d'Astra Trident.
+
--

WARNING: Vous pouvez configurer l'interface REST de Trident pour écouter et utiliser l'interface 127.0.0.1 (pour IPv4) ou [::1] (pour IPv6) uniquement.

--


====


== Options et indicateurs de commande



=== `create`

Utilisez le `create` Commande d'ajout d'une ressource à Astra Trident.

Du stockage::


[listing]
----
tridentctl create [option]
----
Options:: Ajoutez un système back-end à Astra Trident.




=== `delete`

Utilisez le `delete` Commande de supprimer une ou plusieurs ressources d'Astra Trident.

Du stockage::


[listing]
----
tridentctl delete [option]
----
Options:: Supprimez un ou plusieurs systèmes back-end de stockage d'Astra Trident.
`snapshot`:: Supprimez un ou plusieurs snapshots de volume d'Astra Trident.
`storageclass`:: Supprimez une ou plusieurs classes de stockage d'Astra Trident.
`volume`:: Supprimez un ou plusieurs volumes de stockage d'Astra Trident.




=== `get`

Utilisez le `get` Commander pour obtenir une ou plusieurs ressources d'Astra Trident.

Du stockage::


[listing]
----
tridentctl get [option]
----
Options:: Obtenez un ou plusieurs systèmes back-end de stockage avec Astra Trident.
`snapshot`:: Obtenez un ou plusieurs snapshots d'Astra Trident.
`storageclass`:: Obtenez une ou plusieurs classes de stockage avec Astra Trident.
`volume`:: Obtenez un ou plusieurs volumes d'Astra Trident.
Alarmes:: Aide pour les volumes.
`--parentOfSubordinate string`:: Limiter la requête au volume source subordonné.
`--subordinateOf string`:: Limiter la requête aux subordonnés du volume.




=== `images`

Utiliser `images` Drapeaux pour imprimer un tableau des images de conteneur dont Astra Trident a besoin.

Du stockage::


[listing]
----
tridentctl images [flags]
----
Alarmes:: Aide pour les images.
`-v`, `--k8s-version string`:: Version sémantique du cluster Kubernetes.




=== `import volume`

Utilisez le `import volume` Commande permettant d'importer un volume existant vers Astra Trident.

Du stockage::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
Alias:: `volume, v`
Alarmes:: Chemin d'accès au fichier ESV YAML ou JSON.
`-h`, `--help`:: Aide pour le volume.
`--no-manage`:: Créer PV/PVC uniquement. Ne supposez pas la gestion du cycle de vie des volumes.




=== `install`

Utilisez le `install` Drapeaux pour l'installation d'Astra Trident.

Du stockage::


[listing]
----
tridentctl install [flags]
----
Alarmes:: Image conteneur pour le système de télémétrie AutoSupport (par défaut, « netapp/trident AutoSupport:<current-version> »).
`--autosupport-proxy string`:: Adresse/port d'un proxy pour l'envoi de la télémétrie AutoSupport.
`--enable-node-prep`:: Essayez d'installer les modules requis sur les nœuds.
`--generate-custom-yaml`:: Générez des fichiers YAML sans rien installer.
`-h`, `--help`:: Aide pour l'installation.
`--http-request-timeout`:: Remplacez le délai d'expiration des requêtes HTTP pour l'API REST du contrôleur Trident (1m30s par défaut).
`--image-registry string`:: Adresse/port d'un registre d'images interne.
`--k8s-timeout duration`:: Délai d'expiration pour toutes les opérations Kubernetes (3 m0s par défaut).
`--kubelet-dir string`:: Emplacement de l'hôte de l'état interne de kubelet (par défaut "/var/lib/kubelet").
`--log-format string`:: Le format de journalisation d'Astra Trident (text, json) (par défaut, « text »).
`--pv string`:: Le nom du volume persistant utilisé par Astra Trident vérifie qu'il n'existe pas (trident par défaut).
`--pvc string`:: Le nom de la demande de volume persistant utilisée par Astra Trident vérifie qu'elle n'existe pas (par défaut, « trident »).
`--silence-autosupport`:: N'envoyez pas automatiquement de packs AutoSupport à NetApp (valeur par défaut : true).
`--silent`:: Désactivez la plupart des sorties pendant l'installation.
`--trident-image string`:: Image Astra Trident à installer.
`--use-custom-yaml`:: Utilisez tous les fichiers YAML existants qui existent dans le répertoire d'installation.
`--use-ipv6`:: Utilisez IPv6 pour la communication d'Astra Trident.




=== `logs`

Utiliser `logs` Drapeaux pour imprimer les journaux à partir d'Astra Trident.

Du stockage::


[listing]
----
tridentctl logs [flags]
----
Alarmes:: Créez une archive de support avec tous les journaux, sauf indication contraire.
`-h`, `--help`:: Aide pour les journaux.
`-l`, `--log string`:: Journal Astra Trident à afficher. Un de trident|auto|trident-operator|All (auto par défaut).
`--node string`:: Nom du nœud Kubernetes à partir duquel collecter les journaux du pod du nœud.
`-p`, `--previous`:: Obtenez les journaux de l'instance de conteneur précédente, si elle existe.
`--sidecars`:: Procurez-vous les journaux pour les conteneurs sidecar.




=== `send`

Utilisez le `send` Commande permettant d'envoyer une ressource à Astra Trident.

Du stockage::


[listing]
----
tridentctl send [option]
----
Options:: Envoyer une archive AutoSupport à NetApp.




=== `uninstall`

Utiliser `uninstall` Drapeaux pour désinstaller Astra Trident.

Du stockage::


[listing]
----
tridentctl uninstall [flags]
----
Alarmes:: Aide pour la désinstallation.
`--silent`:: Désactivez la plupart des sorties lors de la désinstallation.




=== `update`

Utilisez le `update` Commande permettant de modifier une ressource dans Astra Trident.

Du stockage::


[listing]
----
tridentctl update [option]
----
Options:: Mise à jour d'un système back-end dans Astra Trident.




=== `update backend state`

Utilisez le `update backend state` pour suspendre ou reprendre les opérations back-end.

Du stockage::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
Alarmes:: Réglez sur `suspended` pour interrompre les opérations back-end. Réglez sur `normal` pour reprendre les opérations back-end. Lorsqu'il est réglé sur `suspended`:
+
--
* `AddVolume`, `CloneVolume`, `Import Volume`, `ResizeVolume` sont en pause.
* `PublishVolume`, `UnPublishVolume`, `CreateSnapshot`, `GetSnapshot`, `RestoreSnapshot`, `DeleteSnapshot`, `RemoveVolume`, `GetVolumeExternal`, `ReconcileNodeAccess` et restent disponibles.


--
`-h`, `--help`:: Aide pour l'état du back-end.




=== `version`

Utiliser `version` indicateurs pour imprimer la version de `tridentctl` Et le service exécutant Trident.

Du stockage::


[listing]
----
tridentctl version [flags]
----
Alarmes:: Version client uniquement (aucun serveur requis).
`-h, --help`:: Aide pour la version.

